### ISSUE TITLE
Create login page

### ISSUE THREAD

**Issue by dchanman** [dchanman/tinder-plus-plus#13]
Users should be able to:
- log in with existing credentials as a user
- create a new account as a user
- log in as a business
- create a new account as a business

**Comment by peterysc** [comment]
Store userID and password to the database

**Comment by peterysc** [comment]
using AJAX, username and hashPW will be passed to the DB. 
- query for username and hashPW
  if (found){
  loginSuccessful = True}
  not found = loginSuccessful = false
